{{- if .Values.server  }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: service-discovery
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.global.cloudConfig }}
    tier: {{ .Values.global.namespaceTier }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
data:
  config.json: |-
    {}
{{- end }}