{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubescape.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.kubescape.name }}-config
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.kubescape.name }}-config
    tier: {{ .Values.global.namespaceTier }}
    kubescape.io/infra: kubescape-config
data:
  config.json: |
    {
      "accountID": "{{ .Values.account }}",
      "clusterName": "{{ regexReplaceAll "\\W+" .Values.clusterName "-" }}"
    }
{{- end }}
