kind: ConfigMap 
apiVersion: v1 
metadata:
  name: host-sensor-definition
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.global.beConfig }}
    tier: {{ .Values.global.namespaceTier }}
data:
  host-sensor-yaml: |-
{{ .Files.Get "assets/host-sensor-definition.yaml" | indent 6 }}