apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.armoVulnScanner.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoVulnScanner.name }}
spec:
  type: {{ .Values.armoVulnScanner.service.type }}
  ports:
    - port: {{ .Values.armoVulnScanner.service.port }}
      targetPort: {{ .Values.armoVulnScanner.service.targetPort }}
      protocol: {{ .Values.armoVulnScanner.service.protocol }}
  selector:
    app: {{ .Values.armoVulnScanner.name }}