{{ template "account_guid" . }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.global.beConfig }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.global.beConfig }}
    tier: {{ .Values.global.namespaceTier }}
data:
  clusterData: |
    {
      "ociImageURL": "",
      "notificationWSURL": "{{ .Values.armoNotificationService.name }}:{{ .Values.armoNotificationService.websocketService.port }}",
      "notificationRestURL": "{{ .Values.armoNotificationService.name }}:{{ .Values.armoNotificationService.httpService.port }}",
      "vulnScanURL": "{{ .Values.armoVulnScanner.name }}:{{ .Values.armoVulnScanner.service.port }}",
      "kubescapeURL": "{{ .Values.armoKubescape.name }}:{{ .Values.armoKubescape.service.port }}",
      "oracleURL": "",
{{- if eq .Values.environment "dev" }}      
      "eventReceiverREST": "{{ .Values.devEventReceiverHttpUrl }}",
      "postman": "wss://{{ .Values.devPostmanUrl }}",
      "eventReceiverWS": "{{ .Values.devK8sReportUrl }}",
      "masterNotificationServer": "wss://{{ .Values.devMasterNotificationService }}/v1/waitfornotification",
{{- else if eq .Values.environment "staging" }}
      "eventReceiverREST": "{{ .Values.stagingEventReceiverHttpUrl }}",
      "postman": "wss://{{ .Values.stagingPostmanUrl }}",
      "eventReceiverWS": "{{ .Values.stagingK8sReportUrl }}",
      "masterNotificationServer": "wss://{{ .Values.stagingMasterNotificationService }}/v1/waitfornotification",
{{- else }} 
      "eventReceiverREST": "{{ .Values.eventReceiverHttpUrl }}",
      "postman": "wss://{{ .Values.postmanUrl }}",
      "eventReceiverWS": "{{ .Values.k8sReportUrl }}",
      "masterNotificationServer": "wss://{{ .Values.masterNotificationService }}/v1/waitfornotification",
{{- end }}       
      "dashboard": "",
      "portal": "",
      "customerGUID": "{{ .Values.accountGuid }}",
      "clusterGUID": "",
      "clusterName": "{{ regexReplaceAll "\\W+" .Values.clusterName "-" | lower }}"
    }