{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.armoKubescape.name }}-monitor
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app: {{ .Values.armoKubescape.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  namespaceSelector:
    matchNames:
      -  {{ .Values.armoNameSpace }}
  selector:
    matchLabels:
      app: {{ .Values.armoKubescape.name }}
  endpoints:
    - port: http
      path: /v1/metrics
      interval: 120s
      scrapeTimeout: 100s
{{ end }}