kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.armoKubescape.name }}-config
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoKubescape.name }}
    tier: {{ .Values.global.namespaceTier }}  
data:
  config.json: |
    {
      "customerGUID": "{{ .Values.accountGuid }}",
      "clusterName": "{{ regexReplaceAll "\\W+" .Values.clusterName "-" }}"
    }