kind: ConfigMap 
apiVersion: v1 
metadata:
  name: kubescape-job-template
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.global.beConfig }}
    tier: {{ .Values.global.namespaceTier }}
data:
  jobTemplate: |-
    {{ tpl (.Files.Get "assets/armo-kubescape-job-full.yaml") . }}