{{ template "account_guid" . }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.armoKubescape.name }}-config
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoKubescape.name }}
    tier: {{ .Values.global.namespaceTier }}  
data:
  clusterName: {{ regexReplaceAll "\\W+" .Values.clusterName "-" | lower  }}
  customerGUID: {{ .Values.accountGuid }}
  config.json: |
    {
      "customerGUID": "{{ .Values.accountGuid }}",
      "clusterName": "{{ regexReplaceAll "\\W+" .Values.clusterName "-" | lower  }}"
    }