apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: {{ .Values.armoKubescapeScanScheduler.name }}
      namespace: {{ .Values.armoNameSpace }}
      labels:
        app: {{ .Values.armoKubescapeScanScheduler.name }}
        tier: {{ .Values.global.namespaceTier}}
    spec:
      schedule: "{{ .Values.armoScanScheduler.scanSchedule }}"
      jobTemplate:
        spec:
          template:
            spec:
              containers:
              - name: {{ .Values.armoKubescapeScanScheduler.name }}
                image: "{{ .Values.armoKubescapeScanScheduler.image.repository }}:{{ .Values.armoKubescapeScanScheduler.image.tag }}"
                imagePullPolicy: {{ .Values.armoKubescapeScanScheduler.image.pullPolicy }}
                args: 
                  - -method=post
                  - -scheme=http
                  - -host={{ .Values.armoWebsocket.name }}:{{ .Values.armoWebsocket.service.port }}
                  - -path=v1/triggerAction
                  - -headers="Content-Type:application/json"
                  - -path-body=/home/request/request-body.json
                volumeMounts:
                  - name: {{ .Values.armoKubescapeScanScheduler.name }}
                    mountPath: /home/http_requst/request-body.json
                    subPath: request-body.json
                    readOnly: true
              restartPolicy: Never
              automountServiceAccountToken: false
              volumes:
                - name: "request-body-volume" # placeholder
                  configMap:
                    name: {{ .Values.armoKubescapeScanScheduler.name }}
 

          