name: inspektor-e2e-tests

on:
  push:
    branches:
      - inspektor

jobs:
  call-e2e-tests:
    uses: ./.github/workflows/relevancy-e2e-test.yaml
    with:
      BRANCH: "inspektor"
    secrets: inherit
 